### ISSUE TITLE
Split this project rubric so we can use devflow on it

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/FENDp1#1]
# Introduction
Practice my DevFlow by making 1 issue from each major section of the rubric or project specification.
Intend to use git commit template as well.
Later we can modify this repo to include more of my professional work, perhaps in a fork or if time allowed.
# Questions for Udacity
Need to understand how used in the program and how tied to professional profile...and how long those profiles stay live. Are they lifetime?
# Here's the file
[Udacity Reviews.pdf](https://github.com/rudimusmaximus/FENDp1/files/2060922/Udacity.Reviews.pdf)
 - [x] consider putting part of this into readme
 - [x] draft this epic and start the member issues
 - [x] baseline some labels using the current devflow labels
 - [ ] ask about professional profiles and devflow
 - [x] ask advisor about adding devflow to this later
 - [x] setup gitkraken on mac and setup git commit template
 - [x] resubmit

**Comment by rudimusmaximus** [comment]
# Host Images for readme.md
## Glo Board
![image](https://app.gitkraken.com/api/glo/boards/5b1316054f33b715001b0476/attachments/5b160607c9b0cf0e0093b7b8)

## Finished View of Largest breakpoint  
![image](https://user-images.githubusercontent.com/21182598/41140093-2ba8a454-6ab1-11e8-834a-0ce86aaca925.png)
